name: Build

on:
  workflow_call:

permissions:
  pull-requests: write
  statuses: write
  checks: write

jobs:
  assembleDebug:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          ref: "refs/pull/${{ github.event.pull_request.number }}/merge"

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@cd48c8e22733480b66887b42bfeb6c0b88ea1a56
        with:
          bundler-cache: true

      - name: Create release keystore
        run: echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > gradle/keystore/release.jks

      - name: Create local.properties
        run: echo > local.properties

      - name: Build app
        run: ./gradlew :app:assembleDebug
